---
experiment:
  dataset: bpr-netflix
  data_config:
    strategy: fixed
    train_path: ../data/elliot/train.tsv
    test_path: ../data/elliot/test.tsv
  top_k: 1000
  evaluation:
    simple_metrics: [AUC]
  models:
    BPRMF:
      meta:
        save_recs: true
      seed: 13
      epochs: 94
      factors: 128
      lr: 0.0358185390941126
      bias_regularization: 0.0
      user_regularization: 0.004459686555199224
      positive_item_regularization: 0.00005803908333330523
      negative_item_regularization: 0.0059752414343157475
      update_negative_item_factors: true
      update_users: true
      update_items: true
      update_bias: true
