---
experiment:
  dataset: bpr-netflix
  data_config:
    strategy: fixed
    train_path: ../data/elliot/train.tsv
    test_path: ../data/elliot/test.tsv
  top_k: 1000
  evaluation:
    simple_metrics: [AUC]
  models:
    BPRMF_batch:
      meta:
        save_recs: true
      seed: 13
      epochs: 100
      batch_size: 16
      factors: 64
      lr: 0.0054420894863128205
      l_w: 0.0030445108803128723
      l_b: 0.0030445108803128723
      random_seed: 13
